---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
      name: redis
- apiVersion: v1
  kind: Namespace
  metadata:
      name: consul
- apiVersion: v1
  kind: Namespace
  metadata:
      name: zookeeper
- apiVersion: v1
  kind: Namespace
  metadata:
      name: kafka
