apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master-0
spec:
  storageClassName: redis-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/redis-cluster-master-0
  claimRef:
    name: redis-data-redis-master-0
    namespace: redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-slave-0
spec:
  storageClassName: redis-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/redis-cluster-slave-0
  claimRef:
    name: redis-data-redis-replicas-0
    namespace: redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-slave-1
spec:
  storageClassName: redis-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/redis-cluster-slave-1
  claimRef:
    name: redis-data-redis-replicas-1
    namespace: redis
