apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-zookeeper-zookeeper-0
spec:
  storageClassName: zookeeper-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-zookeeper-0
  claimRef:
    name: data-zookeeper-0
    namespace: zookeeper
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-zookeeper-zookeeper-1
spec:
  storageClassName: zookeeper-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-zookeeper-1
  claimRef:
    name: data-zookeeper-1
    namespace: zookeeper
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-zookeeper-zookeeper-2
spec:
  storageClassName: zookeeper-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-zookeeper-2
  claimRef:
    name: data-zookeeper-2
    namespace: zookeeper
