apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-zookeeper-zookeeper-0
spec:
  storageClassName: zookeeper-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-zookeeper-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-zookeeper-zookeeper-1
spec:
  storageClassName: zookeeper-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-zookeeper-1
