apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master-0
spec:
  storageClassName: consul-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/consul
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-slave-0
spec:
  storageClassName: consul-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/consul
---
