apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elasticsearch-data-0
spec:
  storageClassName: elk-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-elasticsearch-data-0
  claimRef:
    name: data-elasticsearch-data-0
    namespace: elasticsearch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elasticsearch-data-1
spec:
  storageClassName: elk-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-elasticsearch-data-1
  claimRef:
    name: data-elasticsearch-data-1
    namespace: elasticsearch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elasticsearch-master-0
spec:
  storageClassName: elk-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/data-elasticsearch-master-0
  claimRef:
    name: data-elasticsearch-master-0
    namespace: elasticsearch
