---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    type: local
spec:
  storageClassName: redis-stg
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/infrausr/redis"
  claimRef:
    namespace: redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-replica
  labels:
    type: local
spec:
  storageClassName: redis-stg
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/infrausr/redis"
  claimRef:
    namespace: redis
