apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-cluster-master-0
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/redis-cluster-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-cluster-slave-0
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/infrausr/redis-cluster-slave-0
